<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $document['title'] }} - MyDispatch</title>
    <style>
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            background: #525659;
            margin: 0;
            padding: 40px;
            display: flex;
            justify-content: center;
        }

        .page {
            background: white;
            width: 210mm;
            min-height: 297mm;
            padding: 20mm;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
            box-sizing: border-box;
            position: relative;
        }

        .header {
            border-bottom: 2px solid #8b5cf6;
            padding-bottom: 20px;
            margin-bottom: 30px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .logo {
            font-size: 24px;
            font-weight: bold;
            color: #1f2937;
        }

        .logo i {
            color: #8b5cf6;
        }

        h1 {
            font-size: 24px;
            margin: 0;
            color: #1f2937;
        }

        .content {
            color: #374151;
            line-height: 1.6;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th,
        td {
            border: 1px solid #e5e7eb;
            padding: 12px;
            text-align: left;
        }

        th {
            background: #f9fafb;
            font-weight: 600;
        }

        .footer {
            position: absolute;
            bottom: 20mm;
            left: 20mm;
            right: 20mm;
            text-align: center;
            font-size: 12px;
            color: #9ca3af;
            border-top: 1px solid #e5e7eb;
            padding-top: 10px;
        }

        @media print {
            body {
                background: white;
                padding: 0;
            }

            .page {
                box-shadow: none;
                width: 100%;
                height: auto;
            }
        }
    </style>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
</head>

<body>
    <div class="page">
        <div class="header">
            <div class="logo">
                <i class="fas fa-truck"></i> MyDispatch
            </div>
            <div>
                {{ date('F j, Y') }}
            </div>
        </div>

        <h1>{{ $document['title'] }}</h1>

        <div class="content">
            {!! $document['content'] !!}
        </div>

        <div class="footer">
            Generated by MyDispatch Logistics System | Confidential Document
        </div>
    </div>
</body>

</html>